### ISSUE TITLE
Undefined vars

### ISSUE THREAD

**Issue by DirtyRacer1337** [Serechops/Jizzarr#2]
`paginate_query`
https://github.com/Serechops/Jizzarr/blob/a5870f62736827762eea4bcdc34c8445b7f232bb/app.py#L256
https://github.com/Serechops/Jizzarr/blob/a5870f62736827762eea4bcdc34c8445b7f232bb/app.py#L320

`currentScenes`
https://github.com/Serechops/Jizzarr/blob/a5870f62736827762eea4bcdc34c8445b7f232bb/app.py#L1494

**Comment by Serechops** [comment]
Defined paginate_query
Removed the 'get_all_urls' and 'stop_all_urls' routes as this function no longer needs to exist. 
This will be implemented in v0.16

**Comment by Serechops** [comment]
v0.16 pushed. Issues should now be resolved. https://github.com/Serechops/Jizzarr/commit/8d14c65e093281cb2cc27251c298f42cd287790b
