### ISSUE TITLE
paginate_query

### ISSUE THREAD

**Issue by DirtyRacer1337** [Serechops/Jizzarr#4]
`paginate_query` defined two times

https://github.com/DirtyRacer1337/Jizzarr/commit/8d14c65e093281cb2cc27251c298f42cd287790b#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959R254-R257

https://github.com/DirtyRacer1337/Jizzarr/commit/8d14c65e093281cb2cc27251c298f42cd287790b#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959R326-R327

**Comment by DirtyRacer1337** [comment]
also similar problem

same method and var `stop_populate_sites`
https://github.com/DirtyRacer1337/Jizzarr/blob/8d14c65e093281cb2cc27251c298f42cd287790b/app.py#L1391

**Comment by DirtyRacer1337** [comment]
and I'm not even saying that usage global sucks :)

**Comment by Serechops** [comment]
> `paginate_query` defined two times
> 
> [DirtyRacer1337@8d14c65#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959R254-R257](https://github.com/DirtyRacer1337/Jizzarr/commit/8d14c65e093281cb2cc27251c298f42cd287790b#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959R254-R257)
> 
> [DirtyRacer1337@8d14c65#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959R326-R327](https://github.com/DirtyRacer1337/Jizzarr/commit/8d14c65e093281cb2cc27251c298f42cd287790b#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959R326-R327)


Removed second instance of paginate_query https://github.com/Serechops/Jizzarr/commit/408f48cde1f662177214b8791677a2a0fe9b0af1

**Comment by DirtyRacer1337** [comment]
also three `# Configure logging`

**Comment by Serechops** [comment]
> also three `# Configure logging`

Pfft...can never have enough logging...lmao
