### ISSUE TITLE
Error suggesting matches: Error 500: {"error":"cannot unpack non-iterable nt.DirEntry object"}

### ISSUE THREAD

**Issue by zzfet** [Serechops/Jizzarr#9]
From what I can tell, this issue only seems to affect the executable bundle version of Jizzarr. When attempting the same reproduction steps on the 'raw' Python version, Jizzarr behaves as expected.

**Environment information**

- Database was originally created with Jizzarr v0.14.
- Running on Windows 11 23H2.
- I am using the executable bundle version of Jizzarr v0.16.
- Videos are on a mapped network drive (X:)
- Jizzarr is running as the logged-in user, not as administrator.

**Steps to reproduce**
- Start Jizzarr v0.16 with a database originally created by Jizzarr v0.14 in instances/
- Go to 'My Collection' and select a studio that existed before upgrading to v0.16.
- Verify that a home directory is set.
- Click 'Suggest Matches'.
- Result: Error pop-up reading: "Error suggesting matches: Error 500: {"error":"cannot unpack non-iterable nt.DirEntry object"}"

**Attempts to resolve**
- Set home directory manually again. Result: No change.
- Delete and recreate site and attempt to rematch all scenes. Result: No change.

**Comment by DirtyRacer1337** [comment]
it's already fixed in code, but not in exe
